name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  call-shared-keep-alive:
    uses: RSKNET/Github-Actions/.github/workflows/supabase-keep-alive.yml@main
    secrets:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
